language: node_js
node_js:
- 0.1
branches:
  only:
  - master
before_install:
- npm install -g hexo
install:
- npm install
before_script:
- git config --global push.default simple
- git config --global user.name "yantze"
- git config --global user.email 'yantze@126.com'
- git submodule update --init --recursive
script:
- hexo generate
- hexo deploy
after_success:
- cd .deploy
- git add -A .
- git commit -m 'Site updated'
- git push origin gh-pages
env:
  global:
  - secure: AAAtOFeBLK4gRGVshxGzxpSeHs1eJ45jcg/kV2Uvyny/ffvw4/r61C1Zslezi2fT1kIbMuEBAD46PZmqXDTNnKqW9NFBQz4WAFyClUQ4YF/l4JmmgGzy3VZKHSk4q6zfm7D7nsffgN+Z94nZz4AE+pv0AD3VJ+U5iIvWoihcjds=
