language: node_js
node_js:
- 0.1
branches:
  only:
  - master
before_install:
- npm install -g hexo
install:
- npm install
before_script:
- git config --global user.name "yantze"
- git config --global user.email 'yantze@126.com'
- git submodule update --init --recursive

script:
- hexo generate
- cp -r public/* .deploy
- git add -A .
- git commit -m 'Site updated'
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
after_success:
env:
  global:
    secure: Aeta26PF+6bVXkZyiv1GIZS0L8eiTSTokZWLFVFNuWAXM8Ct/6/TdTgYEHYIrAvC+/CMelI2XtS6m1oaWdFZaHMl5jX94ABtqB34MrI5NYR30qPmDpzviAa4L7Jt6oJGXxQw2kGM365GbxKhTdaCIp853XTqvXZt3MLEH1SJp5M=
