language: node_js
node_js:
  - 0.1
branches:
  only:
  - master
before_install:
install:
before_script:
  - git config --global push.default simple
  - git config --global user.name 'yantze'
  - git config --global user.email 'yantze@126.com'
script:
after_success:
